<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<LangVersion>10.0</LangVersion>
		<UseWPF>true</UseWPF>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<PathMap>$(MSBuildProjectDirectory)=$(MSBuildProjectName)</PathMap>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\AutoGrid\AutoGrid.csproj" />
	</ItemGroup>

</Project>
